name: first
on: [push, workflow_dispatch]
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - id: ec2-deploy-action
        name: ec2 deploy action
        #uses: docker://registry.saas-dev.beescloud.com/staging/sshactions:latest
        shell: bash
        
        run: |
        

          array=("${{secrets.TEST_SECRET}}")
          len=${#arrat[@]}
          echo $len
          for index in "${!array[@]}"
          do
              echo $len
              echo "${array[index]}" >> data.pem
          done
          chmod 400 data.pem
            content=$(cat data.pem)
          if [ "$kvalue" == "$content" ];then
               echo " matched"
              else
              echo "Not matched"
          fi
          dest="ubuntu@ec2-35-167-23-60.us-west-2.compute.amazonaws.com"
          ssh -V
          ssh -i data.pem $dest  
          
