name: first
on: [push, workflow_dispatch]
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - id: ec2-deploy-action
        name: ec2 deploy action
        #uses: docker://registry.saas-dev.beescloud.com/staging/sshactions:latest
        shell: bash
        env:
          SSH_KEY: ${{secrets.TEST_SECRET}}
        run: |
          a=$(echo "$SSH_KEY" | base64)
          #echo $a
          #decode it
          b=$(echo "$a" | base64 --decode)
          echo $b
          #echo $b > data.pem
          #chmod 400 data.pem
          #cat data.pem
          #dest="ubuntu@ec2-35-167-23-60.us-west-2.compute.amazonaws.com"
        
          # ssh version 
          #ssh -V
          #ssh -i data.pem $dest  
