name: first
on: [push, workflow_dispatch]
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TEST_SECRET }}

        
      - id: ec2-deploy-action
        name: ec2 deploy action
        #uses: docker://registry.saas-dev.beescloud.com/staging/sshactions:latest
        shell: bash
        run: |
         
          echo -n -e "${{ secrets.TEST_SECRET }}" >> data.pem
          chmod 400 data.pem
          cat data.pem
          dest="ubuntu@ec2-35-167-23-60.us-west-2.compute.amazonaws.com"
          ssh -V
          ssh $dest  
          
