name: first
on: [push, workflow_dispatch]
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - id: ec2-deploy-action
        name: ec2 deploy action
        #uses: docker://registry.saas-dev.beescloud.com/staging/sshactions:latest
        shell: bash
        run: |
        
          kvalue="${{ secrets.TEST_SECRET }}"
          #get begin 
          prefix=${kvalue%%----- *}
          pidx=${#prefix}+5
          begin="${kvalue:0:$pidx}"
          echo "$begin"
        
          #get end
          suffix=${kvalue%*-----END*}
          sidx=${#suffix}
          end="${kvalue:$sidx}"
        
          #get mid
          mid="${kvalue#*$begin }"
          mid="${mid% $end*}"
        
          echo $begin > data.pem
          # replace all spaces with new line
          echo "${mid}" | tr -s "[:space:]" "\\n" >> data.pem
          echo $end >> data.pem
          chmod 400 data.pem
          dest="ubuntu@ec2-35-167-23-60.us-west-2.compute.amazonaws.com"
        
          # ssh version 
          ssh -V
          ssh -i result.pem $dest  
