name: first
on: [push, workflow_dispatch]
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - id: ec2-deploy-action
        name: ec2 deploy action
        #uses: docker://registry.saas-dev.beescloud.com/staging/sshactions:latest
        shell: bash
        run: |

          set -x
        
        
        
          echo "${{ secrets.TEST_SECRET }}" | tr -s  "\\n" > result.pem
       
          file_size=$(stat result.pem)
          echo $file_size  

          chmod 400 result.pem
          dest="ubuntu@ec2-35-167-23-60.us-west-2.compute.amazonaws.com"
          # ssh version 
          ssh -V
          set -x
          ssh -i result.pem $dest
